services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "loja"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "SenhaDoRoot"
    ports:
      - "30306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql2
volumes:
  my-db:
